# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bef135da029dc8a4c100c716db6fd488f54445ad396fa025c70e5dec95fee0ddb48df63e98a2b1f47a8f51b1fc24ba50c1f7b7da0f8fb0a4405a2f4dec1075c0

test:
  secret_key_base: 487aa354c36639f24345f9be396b94c49095306bfb008de1c2bff6ebea343caca2e80ff3670fc3b42b82384c4f89922c4f5fc9c705a64934c1296adc1228a1af

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
